### ISSUE TITLE
Quests issues

### ISSUE THREAD

**Issue by DawEdhel** [JayH2971/dfunity-questpacks#6]
Hi,

I have some problems with several quests on DFU v. 0.10.23:

1) [JHFG027](https://github.com/JayH2971/dfunity-questpacks/blob/master/QuestPacks/QP1/FightersGuild/JHFG027.txt) - Dark Sayings

Taking the quest and then reading a letter causes nothing to happen afterwards.
Using debugger, it shows that quest gets finished, but next part (the a one) won't start.

2) [JHKN004](https://github.com/JayH2971/dfunity-questpacks/blob/master/QuestPacks/QP1/KnightlyOrders/JHKN004.txt) - City Under Siege

I am pretty sure that quest has never been picked/started, and yet I can't start it. A questgiver replies with following quotes:

"Yah, I had work. But the situation has resolved itself. Thanks anyway."
"That lousy... someone has been spreading rumors that i need help. I don't need any help in anything."
"Well, I had work, but I hired the Fighters Guild to do it."

The last quote reminded of similar, completed sooner quest, which is [Surprise Invasion](https://github.com/JayH2971/dfunity-questpacks/blob/master/QuestPacks/QP1/FightersGuild/JHFG019.txt), and they might be intertwined with each other in some way.

Also it's probably worth to mention that I'm using a mod that allows to pick a certain quest from the list of available ones. This might causes mods incompatibility in a way, that you're allowed to start uncompleted/repetitive quests, but not filtered of linked ones.

**Comment by DawEdhel** [comment]
3. [JHDB018](https://github.com/JayH2971/dfunity-questpacks/blob/master/QuestPacks/QP1/DarkBrotherhood/JHDB018.txt) - The Debt Collector

When you get a townperson as the target, that willing to pay you gold, and declining to get bribed leads to nothing afterwards. Looking into the quest logic, I guess, there is an missing instruction to spawn a hostile foe to deal with and proceed further.

**Comment by DawEdhel** [comment]
4. [JHDB021](https://github.com/JayH2971/dfunity-questpacks/blob/master/QuestPacks/QP1/DarkBrotherhood/JHDB021.txt) - To Kill an Ambassador

When arrived and giving the yes answer, nothing afterward happens. As similar to the first quest here, the a part won't get started.

**Comment by JayH2971** [comment]
Thanks for reporting. 1 and 4 are based on a problem with the quest list I just fixed, so the most recent version will work properly; you can find the change on Nexusmods. I just fixed 3; that was a simple programming failure, I never came back to put that one in :grinning: 

2 just means you're in a city without the required resources (specifically, a palace).

I very rarely check github, so sorry I haven't gotten to this sooner. But thank you for telling me.
