### ISSUE TITLE
JHIM021 Incorrect pronoun used

### ISSUE THREAD

**Issue by TheKat** [JayH2971/dfunity-questpacks#7]
Upon completing this quest, the following appeared in my log:

"Lysyna Buckinghouse will pay me 112 gold to help she get vengeance on someone named..."

That should be:

"Lysyna Buckinghouse will pay me 112 gold to help **her** get vengeance on someone named..."

![JHIM021](https://user-images.githubusercontent.com/4400793/94100363-547aed80-fde2-11ea-90cc-12fe725ea672.jpg)

**Comment by TheKat** [comment]
Seems to be at https://github.com/JayH2971/dfunity-questpacks/blob/2e7501f617aff215a6fd5c2eef321e6755709af8/QuestPacks/QP1/Commoner/JHIM021.txt#L96

Attaching a save.


[SAVE15.zip](https://github.com/JayH2971/dfunity-questpacks/files/5273442/SAVE15.zip)

**Comment by JayH2971** [comment]
Found and corrected. Thank you :grinning:
