### ISSUE TITLE
Proposal for quest JHTG003 

### ISSUE THREAD

**Issue by Pekkape** [JayH2971/dfunity-questpacks#8]
I have a proposal for a slightly change in the quest JHTG003 for the Thief Guild, so this is not really an issue or bug at all, well in one way it is a bug...  ;)

I am an experienced thief and in all other TES games, we never hurt victims. I did spend 4 hours yesterday, trying to pickpocket the target and all I got was some useless marbles, some dust, some half eaten food and a couple of gold and some skill points of course.  :D

The quest giver do not mention that we do need to hurt the target some as he only inform us that we will most likely be involved in some fighting and that we should not kill the target, but nothing about spanking it as we never do that as thieves, ever. So instead of spending 4 hours, we could at least be given that info...  Not making odd guesses as this is odd, at least for me and not normal.

So how do I know that I need to spank the target? Well I get that impression when I read the JHTG003.txt, which I did before I went to bed.

It was boring 4 hours, going through the door to the tavern 100-548.3 times, well i lost count really, pickpocket and go out again and go back in, again, again and again....  

...and again...

Heal, cast Chameleon and go back in again...

//Pekka  :D

**Comment by JayH2971** [comment]
I'll change the dialogue to say this:

<ce>        Make sure you go at night, like after ten. Less ruckus
<ce>        that way. This won't take pickpocketing; a good, heavy
<ce>      smack should let you get it into your hands, but I'm just
<ce>       gonna say this once: if you kill the carrier, there will
<ce>         be no forgiveness for you. At least not on my part.

Thanks for the feedback.

**Comment by Pekkape** [comment]
Sounds very cool.  :D  Very well made. I love this quest package as it did take Daggerfall to a new dimension. It is increadable that this game I played 1995 is still so fun. It is addictive...
